env:
  browser: true
  es2022: true
  node: false
  serviceworker: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  max-len:
    - warn
    - code: 120
      ignoreComments: true
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  no-multiple-empty-lines:
    - warn
    - max: 2
      maxBOF: 0
      maxEOF: 0
  indent:
    - error
    - tab
    - SwitchCase: 1
  semi:
    - warn
    - always
  no-tabs: off
  space-before-function-paren:
    - warn
    - anonymous: never
      named: never
      asyncArrow: always
  default-case: warn
  generator-star-spacing:
    - warn
    - before: false
      after: true
  object-curly-newline:
    - warn
    - multiline: true
  space-in-parens: warn
  require-jsdoc: off
  valid-jsdoc: warn
  spaced-comment: off
  dot-notation: off
  no-useless-constructor: off
  '@typescript-eslint/no-unsafe-assignment':
    - warn


# Docs
# Rules & Fixable errors - https://eslint.org/docs/rules/
# ESLint TypeScript - https://typescript-eslint.io/docs/
# Plugin: Import - https://github.com/import-js/eslint-plugin-import
# JSDoc - https://jsdoc.app/index.html
