env:
  browser: true
  es2021: true
  node: false
  serviceworker: true
extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
#  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
#globals:
#  ENV: readonly
plugins:
  - '@typescript-eslint'
rules:
  max-len:
    - warn
    - code: 120
      ignoreComments: true
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  no-multiple-empty-lines:
    - warn
    - max: 2
      maxBOF: 0
      maxEOF: 0
  indent:
    - error
    - tab
    - SwitchCase: 1
  no-tabs: off
  default-case: warn
  require-jsdoc: off
  valid-jsdoc: warn
  block-spacing: off
  arrow-parens: off
  operator-linebreak: off
  no-duplicate-imports: warn
  comma-dangle:
    - warn
    - never
  object-curly-newline:
    - warn
    - multiline: true
  object-curly-spacing:
    - warn
    - always
  space-before-function-paren:
    - warn
    - anonymous: never
      named: never
      asyncArrow: always
  spaced-comment: off
  space-in-parens: warn
  generator-star-spacing: off
  guard-for-in: off



# Docs
# ESLint TypeScript - https://typescript-eslint.io/docs/
# Fixable ESLint errors - https://eslint.org/docs/rules/
# JSDoc - https://jsdoc.app/index.html
#
# # RULES
# Indent - https://eslint.org/docs/rules/indent
# Max length - https://eslint.org/docs/rules/max-len#enforce-a-maximum-line-length-max-len
#





